### DISCUSSION TITLE
How are environment variables loaded from "config.yaml" in a development environment?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [enviodev/hyperindex#576] [Q&A] [answered]
From the docs on [fallback RPCs](https://docs.envio.dev/docs/HyperIndex/hypersync#improving-resilience-with-rpc-fallback), it appears to be possible to use environment variables in the `config.yaml` file. I've added mine like this:

```yaml
name: Greeter
description: Greeter indexer
networks:
  - id: 1
     rpc: https://mainnet.infura.io/v3/{ENVIO_INFURA_API_KEY}
```

But it's not clear to me where should I put the environment variables when running `envio dev`. In an `.env` file? If yes, where should the `.env` file be located? At the same level with `config.yaml`?

I couldn't find any information about this in the docs.
