### ISSUE TITLE
Indexer gets stuck while indexing in multiple chains

### ISSUE THREAD

**Issue by 0xkenj1** [enviodev/hyperindex#189]
**Describe the bug**
I am trying to index 15 blockchains at the same time some are not indexing as expected, chainIds 250, 42161, 11155111  and 1329 are getting stuck. Also errors are not returning ChainId to let know which is the chain that is failing.

The initial log is: 

```
[10:08:32.141] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 10

[10:08:32.149] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 1

[10:08:32.150] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 42

[10:08:32.151] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 137

[10:08:32.151] INFO (47160): Initializing ChainFetcher with RPC worker
    chainId: 1329

[10:08:32.151] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 8453

[10:08:32.153] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 42161

[10:08:32.163] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 250

[10:08:32.163] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 324

[10:08:32.164] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 42220

[10:08:32.164] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 43114

[10:08:32.164] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 534352

[10:08:32.166] INFO (47160): Initializing ChainFetcher with HyperSync worker
    chainId: 11155111

[10:02:21.029] INFO (46463): All events have been fetched, they should finish processing the handlers soon.
    chainId: 250

[10:02:21.334] INFO (46463): All events have been fetched, they should finish processing the handlers soon.
    chainId: 42161
```

**To Reproduce**

E.g.
1. Set this config 

```
name: Allo Indexer
unordered_multichain_mode: true
raw_events: true
##########################
#       CONTRACTS        #
##########################
contracts:
- name: Allo
  handler: src/handlers/Allo.ts
  events:
    - event: PoolCreated(uint256 indexed poolId, bytes32 indexed profileId, address strategy, address token, uint256 amount, (uint256,string) metadata)
    - event: RoleGranted(uint64 indexed roleId, address indexed account, uint32 delay, uint48 since, bool newMember)
    - event: PoolMetadataUpdated(uint256 indexed poolId, (uint256,string) metadata)
    - event: PoolFunded(uint256 indexed poolId, uint256 amount, uint256 fee)
    - event: RoleRevoked(uint64 indexed roleId, address indexed account)
- name: Registry
  handler: src/handlers/Registry.ts
  events:
    - event: ProfileCreated(bytes32 indexed profileId, uint256 nonce, string name, (uint256,string) metadata, address owner, address anchor)
    - event: ProfileMetadataUpdated(bytes32 indexed profileId, (uint256,string) metadata)
    - event: ProfileNameUpdated(bytes32 indexed profileId, string name, address anchor)
    - event: ProfileOwnerUpdated(bytes32 indexed profileId, address owner)
- name: GeneralStrategy
  handler: src/handlers/GeneralStrategy.ts
  events:

    ########################## ALLO v2 ##########################
    # Registered
    - event: Registered(address indexed recipientId, bytes data, address sender)
      name: RegisteredWithSender
    - event: Registered(address indexed _recipient, bytes _data)
      name: RegisteredWithData

    #TimestampsUpdated
    - event: TimestampsUpdated(uint64 startTime, uint64 endTime, address sender)
      # Keep in mind that parameters could be allocation or registration timestamps in this case. It depends on the contract.
      name : TimestampsUpdated
    - event: TimestampsUpdated(uint64 registrationStartTime, uint64 registrationEndTime, uint64 allocationStartTime, uint64 allocationEndTime, address sender)
      name : TimestampsUpdatedWithRegistrationAndAllocation
    
    

    # DistributionUpdated
    - event: DistributionUpdated(bytes32 merkleRoot, (uint256,string) metadata)

    # FundsUpdated
    - event: FundsDistributed(uint256 amount, address grantee, address indexed token, address indexed recipientId)
    
    # Distributed
    - event: Distributed(address indexed recipientId, address recipientAddress, uint256 amount, address sender)
      name: DistributedWithRecipientAddress
    - event: Distributed(address indexed _recipient, bytes _data)
      name: DistributedWithData
    - event: Distributed(address indexed sender, int96 flowRate)
      name: DistributedWithFlowRate

    # Allocated
    - event: Allocated(address indexed recipientId, uint256 amount, address token, address sender, address origin)
      name: AllocatedWithOrigin
    - event: Allocated(address indexed _recipient, address indexed _sender, uint256 _amount, bytes _data)
      name: AllocatedWithData
    - event: Allocated(address indexed recipientId, uint256 amount, address token, address sender)
      name: AllocatedWithToken
    - event: Allocated(address indexed recipientId, uint256 votes, address allocator)
      name: AllocatedWithVotes
    - event: Allocated(address indexed recipientId, uint8 status, address sender)
      name: AllocatedWithStatus

    # AllocatedWithNft
    - event: AllocatedWithNft(address indexed recipientId, uint256 votes, address nft, address allocator)

    # DirectAllocated
    - event: DirectAllocated(address indexed recipient, uint256 amount, address token, address sender)

    # RecipientStatusUpdated
    - event: RecipientStatusUpdated(address indexed recipientId, uint256 applicationId, uint8 status, address sender)
      name: RecipientStatusUpdatedWithApplicationId
    - event: RecipientStatusUpdated(address indexed recipientId, uint8 recipientStatus, address sender)
      name: RecipientStatusUpdatedWithRecipientStatus
    - event: RecipientStatusUpdated(uint256 indexed rowIndex, uint256 fullRow, address sender)
      name: RecipientStatusUpdatedWithFullRow

    # ########################## ALLO v2.1 ##########################
    
    # # AllocationExtension
    # - event: AllocationTimestampsUpdated(uint64 allocationStartTime, uint64 allocationEndTime, address sender)
    
    # # AllocationAllowlistExtension
    # - event: AllocatorsRemoved(address[] allocators, address sender)
    # - event: AllocatorsAdded(address[] allocators, address sender)

    # # MilestoneExtension
    # - event: MaxBidIncreased(uint256 maxBid)
    # - event: SetBid(address indexed bidderId, uint256 newBid)
    # - event: MilestoneSubmitted(uint256 milestoneId)
    # - event: MilestoneStatusChanged(uint256 indexed milestoneId, uint8 status)
    # - event: MilestonesSet(uint256 milestonesLength)

    # # RecipientsExtension
    # - event: UpdatedRegistration(address indexed recipientId, bytes data, address sender, uint8 status)
    # - event: RecipientStatusUpdated(uint256 indexed rowIndex, uint256 fullRow, address sender)
    # - event: RegistrationTimestampsUpdated(uint64 registrationStartTime, uint64 registrationEndTime, address sender)





##########################
#        NETWORKS        #
##########################
networks:
#######################
#       MAINNET       #
#######################
- id: 1 # mainnet
  start_block: 18486688
  contracts:
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1
  - name: GeneralStrategy
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3

- id: 10 # optimism
  start_block: 111678968
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 11155111 # sepolia
  start_block: 4617051
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 250 # fantom
  start_block: 77624278
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 42161 # arbitrum
  start_block: 146489425
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1


- id: 137 # polygon
  start_block: 49466006
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 8453 # base
  start_block: 6083365
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 324 # zksync-era-mainnet
  start_block: 31154341
  contracts:
  - name: Registry
    address:
    - 0xaa376Ef759c1f5A8b0B5a1e2FEC5C23f3bF30246
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x9D1D1BF2835935C291C0f5228c86d5C4e235A249

- id: 43114 # avalanche
  start_block: 34540051
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 534352 # scroll
  start_block: 2683205
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1

- id: 42220 # celo-mainnet
  start_block: 22257475
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1


- id: 42 # lukso-mainnet
  start_block: 2400000
  contracts:
  - name: Registry
    address:
    - 0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  - name: GeneralStrategy
  - name: Allo
    address:
    - 0x1133eA7Af70876e64665ecD07C0A0476d09465a1
```
2. Using empty handlers for all the events
3. Graphql schema (don't think it affects since iam using empty handlers):
```
type Metadata {
  id: ID!
  protocol: BigInt!
  pointer: String!
}


##########################
#       Allo Core        #
##########################
type PoolCreated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  poolId: BigInt!
  profileId: String!
  strategy: String!
  token: String!
  amount: BigInt!
  metadata: Metadata!
}

type PoolMetadataUpdated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  poolId: BigInt!
  metadata: Metadata!
}

type PoolFunded {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  poolId: BigInt!
  amount: BigInt!
  fee: BigInt!
}

type RoleGranted {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  roleId: BigInt!
  account: String!
  delay: BigInt!
  since: BigInt!
  newMember: Boolean!
}

type RoleRevoked {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  roleId: BigInt!
  account: String!
}

##########################
#      Allo Registry     #
##########################


type ProfileCreated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  profileId: String!
  nonce: BigInt!
  name: String!
  metadata: Metadata!
  owner: String!
  anchor: String!
}

type ProfileMetadataUpdated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  profileId: String!
  metadata: Metadata!
}

type ProfileNameUpdated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  profileId: String!
  name: String!
  anchor: String!
}

type ProfileOwnerUpdated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  profileId: String!
  owner: String!
}

##########################
#      Allo Strategy     #
##########################

### Registered ###
type RegisteredWithSender {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  data: Bytes!
  sender: String!
}

type RegisteredWithData {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipient: String!
  data: Bytes!
}

### TimestampsUpdated ###
type TimestampsUpdatedWithRegistrationAndAllocation {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  registrationStartTime: BigInt!
  registrationEndTime: BigInt!
  allocationStartTime: BigInt!
  allocationEndTime: BigInt!
  sender: String!
}

type TimestampsUpdatedWithRegistration {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  registrationStartTime: BigInt!
  registrationEndTime: BigInt!
  sender: String!
}

type TimestampsUpdatedWithAllocation {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  allocationStartTime: BigInt!
  allocationEndTime: BigInt!
  sender: String!
}

### DistrubutionUpdated ###

type DistributionUpdated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  merkleRoot: Bytes!
  metadata: Metadata!
}

### FundsDistributed ###
type FundsDistributed {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  amount: BigInt!
  grantee: String!
  token: String!
  recipientId: String!
}

### Distributed ###
type DistributedWithRecipientAddress {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  recipientAddress: String!
  amount: BigInt!
  sender: String!
}

type DistributedWithData {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipient: String!
  data: Bytes!
}

type DistributedWithFlowRate {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  sender: String!
  flowRate: BigInt!
}

### Allocated ###
type AllocatedWithOrigin {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  amount: BigInt!
  token: String!
  sender: String!
  origin: String!
}

type AllocatedWithData {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  sender: String!
  amount: BigInt!
  data: Bytes!
}

type AllocatedWithToken {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  amount: BigInt!
  token: String!
  sender: String!
}

type AllocatedWithVotes {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  votes: BigInt!
  allocator: String!
}

type AllocatedWithStatus {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  status: BigInt!
  sender: String!
}

### AllocatedWithNft ###
type AllocatedWithNft {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  votes: BigInt!
  nft: String!
  allocator: String!
}

### DirectAllocated ###
type DirectAllocated {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipient: String!
  amount: BigInt!
  token: String!
  sender: String!
}

### RecipientStatusUpdated ###
type RecipientStatusUpdatedWithApplicationId {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  applicationId: BigInt!
  status: BigInt!
  sender: String!
}

type RecipientStatusUpdatedWithRecipientStatus {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  recipientId: String!
  recipientStatus: BigInt!
  sender: String!
}

type RecipientStatusUpdatedWithFullRow {
  id: ID!
  blockNumber: Int! @index
  timestamp: Int!
  logIndex: Int!
  srcAddress: String!
  rowIndex: BigInt!
  fullRow: BigInt!
  sender: String!
}
```

**Expected behavior**
Should index all the chains correctly 

**Screenshots**
<img width="1153" alt="Screenshot 2024-09-10 at 10 21 12" src="https://github.com/user-attachments/assets/199298f3-b4b1-420f-b2aa-700cc2e4d1a9">
<img width="1725" alt="Screenshot 2024-09-10 at 10 22 52" src="https://github.com/user-attachments/assets/e4c2cb1f-73ae-4955-9d25-50c833c30156">

**Local (please complete the following information):**
 - Envio version: 2.2.3
 - Node version: v18.20.4
 - pnpm version: pnpm@9.9.0+sha512.60c18acd138bff695d339be6ad13f7e936eea6745660d4cc4a776d5247c540d0edee1a563695c183a66eb917ef88f2b4feb1fc25f32a7adcadc7aaf3438e99c1
 - Docker version (if running locally): Docker version 27.1.1, build 6312585
