### ISSUE TITLE
Can not set `field_selection.transaction_fields.[from|to]` when some chains use custom rpc.

### ISSUE THREAD

**Issue by fewensa** [enviodev/hyperindex#260]
**Describe the bug**

```
# npm run codegen

> ormpexer@0.1.0 codegen
> envio codegen

Error: Failed cli execution

Caused by:
    0: Failed parsing config
    1: The following selected transaction_fields are unavailable for indexing via RPC: From, To
```

**To Reproduce**

for config.yml

```
networks:
  - id: 701 # koi
    rpc_config:
      url: https://koi-rpc.darwinia.network
    start_block: 6180
    contracts:
      - name: ORMP
        address:
          - 0x13b2211a7cA45Db2808F6dB05557ce5347e3634e
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"

```

**Expected behavior**
Success to run codegen

**Screenshots**
---

**Local (please complete the following information):**
 - Envio version 2.4.4
 - Node version v20.10.0
 - pnpm version
 - Docker version (if running locally)

**Hosted Service (please complete the following information):**
 - Envio version
 - Link to the deployed indexer

**Additional context**

Code link: https://github.com/ringecosystem/ormpexer/pull/13/files#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034R150-R155
