### ISSUE TITLE
Feature Request: Templating engine  / support for environment variables via .env files

### ISSUE THREAD

**Issue by Simon0x** [enviodev/hyperindex#315]
Hello, 

this is not a top priority but after talking to multiple developers of what envio is capable of doing, I noticed that a lot would like to have a templating engine and/or support for environment variables.

I think this could be a great feature to adopt usage of Envio compared to subgraphs.
I've setup a workaround in my project which I can share here, however I think it would be great to have an official solution.

<details>
  <summary>Adujustments to package.json</summary>

```
"codegen": "pnpm run config && envio codegen",
"dev": "npx dotenvx run -- envio dev",
"start": "npx dotenvx run -- ts-node generated/src/Index.bs.js",
"config": "npx dotenvx run -- ts-node ./scripts/render-config-template.ts"
```
</details>

<details>
  <summary>.env file</summary>

```
# This is either mainnet or testnet
TEMPLATE=mainnet
```
</details>

<details>
  <summary>render-config-template.ts</summary>

```
import fs from 'fs';
import ejs from 'ejs';
import { Config } from '../src/types/config.ts';
import { getLoadedConfig } from '../src/config';

type ConfigOverride = Config & {
  jointUniswapPoolContracts: string;
};

if (!process.env.TEMPLATE) {
  console.error('No TEMPLATE environment variable set');
  process.exit(1);
}

if (process.env.TEMPLATE !== 'mainnet' && process.env.TEMPLATE !== 'testnet') {
  console.error('Invalid TEMPLATE environment variable set');
  process.exit(1);
}

const loadedConfig = getLoadedConfig();

const configValues: ConfigOverride = {
  ...loadedConfig,
  jointUniswapPoolContracts: [loadedConfig.uniswapWethBstPoolAddress, loadedConfig.uniswapBstUsdtPoolAddress].join(','),
};

const configTemplate = fs.readFileSync(
  `./templates/template.${process.env.TEMPLATE}.config.yaml`,
  'utf8'
);

const configString = ejs.render(configTemplate, { config: configValues });

const generationWarning = `### This file is autogenerated from the template.config.yaml file in the root of the project ###
### Edit the template.config.yaml file in the root of the project and run \`pnpm run codegen\` to update this file ###
`;

try {
  fs.writeFileSync('./config.yaml', generationWarning + configString);
} catch (e) {
  console.log(e);
}

```
</details>

<details>
  <summary>template.mainnet.config.yaml</summary>

```
name: Blocksquare
field_selection:
  transaction_fields:
    - 'hash'
    - 'transactionIndex'
contracts:
  - name: BlocksquareToken
    abi_file_path: abis/BlocksquareToken.json
    handler: src/handler/Token.ts
    events:
      - event: Transfer
  - name: UniswapPoolV2
    abi_file_path: abis/UniswapPoolV2.json
    handler: src/handler/UniswapPoolV2.ts
    events:
      - event: Swap
networks:
  - id: <%= config.chainId %>
    start_block: <%= config.startBlock %>
    contracts:
      - name: BlocksquareToken
        address:
          - <%= config.blockSquareTokenAddress %>
      - name: UniswapPoolV2
        address: [<%= config.jointUniswapPoolContracts %>]
```
</details>

<details>
  <summary>template.testnet.config.yaml</summary>

```
name: Blocksquare
field_selection:
  transaction_fields:
    - 'hash'
    - 'transactionIndex'
contracts:
  - name: BlocksquareToken
    abi_file_path: abis/BlocksquareToken.json
    handler: src/handler/Token.ts
    events:
      - event: Transfer
  - name: UniswapPoolV2
    abi_file_path: abis/UniswapPoolV2.json
    handler: src/handler/UniswapPoolV2.ts
    events:
      - event: Swap
  # This is used to index mainnet for price feeds
  - name: PriceFeedRegistry
    abi_file_path: ./abis/PriceFeedRegistry.json
    handler: src/handler/PriceFeedRegistryHandler.ts
    events:
      - event: FeedConfirmed
  - name: PriceDataFeed
    abi_file_path: ./abis/PriceDataFeed.json
    handler: src/handler/PriceFeedDataHandler.ts
    events:
      - event: AnswerUpdated
networks:
  ### START PRICE FEED SECTION  ###
  # We fetch the prices of BST and other currencies directly from mainnet as they are not available on testnet
  # Comment this section out if you want fast sync for testing without fetching prices
  - id: 1
    start_block: 0
    contracts:
      - name: PriceFeedRegistry
        address:
          - 0x47fb2585d2c56fe188d0e6ec628a38b74fceeedf
      - name: UniswapPoolV2
        address:
          # Mainnet BST/ETH pool
          - 0x0e85fb1be698e777f2185350b4a52e5ee8df51a6
      - name: PriceDataFeed

  ### END PRICE FEED SECTION ###

  ### START ECOSYSTEM NETWORK SPECIFIC SECTION ###
  - id: <%= config.chainId %>
    start_block: <%= config.startBlock %>
    contracts:
      - name: BlocksquareToken
        address:
          - <%= config.blockSquareTokenAddress %>
  ### END ECOSYSTEM NETWORK SPECIFIC SECTION ###

```
</details>

Maybe we can work out something that can be used as a general method. Because I remember that when using subgraphs, one of the most annoying things was to maintain different environments.

**Comment by JonoPrest** [comment]
Hey @Simon0x, we have this in the pipeline already!

Our V2 hosted service is about to launch and environment variables will be configurable.

It's not implemented yet but the plan is to have the config file accept environment variables much the same as a docker-compose file where you can interpolate environment variables with fallbacks. For eg:

```yaml
networks:
  - id: 1
    rpc_url: ${MAINNET_RPC_URL:-https://my-free-mainnet-rpc.com}
```

Would this be sufficient?
