### ISSUE TITLE
Feature Request: Improve envio indexer to support start_block and end_block per datasource

### ISSUE THREAD

**Issue by Simon0x** [enviodev/hyperindex#316]
Hello envio team,

I'd like to ask to have the option to specify an end_block per datasource rather than per network.
An example use case for us for example is that we have a PropertyFactory that is registering new tokenized properties on the chain. Lets say this is PropertyFactoryV1. Now we deploy a new PropertyFactory, call it PropertyFactoryV2 that will only be used from now on.

This could become very hand in case of upgradeable proxies, where you might push an update that change the signature of the underlying events. In this case you could specify the same proxy contract address with two different handlers as you have a start and end block per handler. 
This idea comes from my usage with subgraphs where it was possible. Example of how it was done there:

```
specVersion: 0.0.4
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/graph-tooling
schema:
  file: ./schema.graphql
indexerHints:
  prune: auto
dataSources:
  - kind: ethereum/contract
    name: Gravity
    network: mainnet
    source:
      address: '0x2E645469f354BB4F5c8a05B3b30A929361cf77eC'
      abi: Gravity
      startBlock: 6175244
      endBlock: 7175245
    context:
      foo:
        type: Bool
        data: true
      bar:
        type: String
        data: 'bar'
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Gravatar
      abis:
        - name: Gravity
          file: ./abis/Gravity.json
      eventHandlers:
        - event: NewGravatar(uint256,address,string,string)
          handler: handleNewGravatar
        - event: UpdatedGravatar(uint256,address,string,string)
          handler: handleUpdatedGravatar
      callHandlers:
        - function: createGravatar(string,string)
          handler: handleCreateGravatar
      blockHandlers:
        - handler: handleBlock
        - handler: handleBlockWithCall
          filter:
            kind: call
      file: ./src/mapping.ts
```

**Comment by JonoPrest** [comment]
Hey @Simon0x,

Thanks for noting all of these features in issues!

Just to unblock you for your use case with upgradeable proxies, we do provide a way to add an "name" alias for an event where the signature has changed.

So for instance you can have:

```yaml
    events:
      - event: NewGravatar(uint256,address,string,string)
      - event: NewGravatar(uint256,address)
        name: NewGravatarUpgraded
```

And write different handlers for these events. It even works if you add/update "indexed" parameters
