### ISSUE TITLE
Dynamic contract registry needs empty address: field

### ISSUE THREAD

**Issue by TimEconometrics** [enviodev/hyperindex#322]
**Describe the bug**
I have to specify address: in my config.yml in order for the dynamic contract registry to work properly. As the dynamic PoolCreated events are not processed in this case. The pools are not saved. 

**To Reproduce**
Works:
```
# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio_indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: PoolFactory
    address:
    - 0x1F98431c8aD98523631AE4a59f267346ea31F984
    handler: src/PoolFactory.ts
    events:
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: NFPM
    address:
    - 0xC36442b4a4522E871399CD717aBDD847Ab11FE88
    handler: src/NFPM.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
    - event: IncreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)
    - event: DecreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)
  - name: UniswapV3Pool
    address:
    # - 0xC2C390c6CD3C4e6c2b70727d35a45e8a072F18cA # EIGEN-WETH
    # - 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640 # WETH-USDC
    handler: src/Pool.ts
    events:
    - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
    - event: Initialize(uint160 sqrtPriceX96, int24 tick)
    - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
    - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
rollback_on_reorg: false
```

Doesnt work (Check UniswapV3Pool for difference):
```
# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio_indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: PoolFactory
    address:
    - 0x1F98431c8aD98523631AE4a59f267346ea31F984
    handler: src/PoolFactory.ts
    events:
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: NFPM
    address:
    - 0xC36442b4a4522E871399CD717aBDD847Ab11FE88
    handler: src/NFPM.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
    - event: IncreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)
    - event: DecreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)
  - name: UniswapV3Pool
    # address:
    # - 0xC2C390c6CD3C4e6c2b70727d35a45e8a072F18cA # EIGEN-WETH
    # - 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640 # WETH-USDC
    handler: src/Pool.ts
    events:
    - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
    - event: Initialize(uint160 sqrtPriceX96, int24 tick)
    - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
    - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
rollback_on_reorg: false
```
