### ISSUE TITLE
More informative error reporting when running `envio codegen`

### ISSUE THREAD

**Issue by PaulRBerg** [enviodev/hyperindex#527]
I just bumped into this error:

```
bun run envio codegen
Error: Failed cli execution

Caused by:
    0: Failed parsing config
    1: EE106: Failed to automatically find HyperSync endpoint for the network. Please provide it manually via the hypersync_config option, or provide an RPC URL for historical sync. Read more in our docs: https://docs.envio.dev/docs/configuration-file
error: "envio" exited with code 1
```

It would be helpful if the CLI provided a specific line or network name where the information is missing.

I currently have no idea which network is causing this error. Here's my `config.yaml` file:

<details><summary>See `config.yaml`</summary>
<p>

```yaml
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yaml-language-server: $schema=../../../node_modules/envio/evm.schema.json
name: sablier-flow
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - from
    - hash
    - to
    - transactionIndex
    - value
contracts:
  - name: SablierFlow_v1_0
    abi_file_path: ../../abi/flow-v1.0/SablierFlow.json
    handler: mappings/v1.0.ts
    events:
      - event: Approval
      - event: ApprovalForAll
      - event: Transfer
      - event: AdjustFlowStream
      - event: CreateFlowStream
      - event: DepositFlowStream
      - event: PauseFlowStream
      - event: RefundFromFlowStream
      - event: RestartFlowStream
      - event: VoidFlowStream
      - event: WithdrawFromFlowStream
  - name: SablierFlow_v1_1
    abi_file_path: ../../abi/flow-v1.1/SablierFlow.json
    handler: mappings/v1.1.ts
    events:
      - event: Approval
      - event: ApprovalForAll
      - event: Transfer
      - event: AdjustFlowStream
      - event: CreateFlowStream
      - event: DepositFlowStream
      - event: PauseFlowStream
      - event: RefundFromFlowStream
      - event: RestartFlowStream
      - event: VoidFlowStream
      - event: WithdrawFromFlowStream
networks:
  - id: 2741
    start_block: 73630
    contracts:
      - name: SablierFlow_v1_0
        address: "0x001f1408515ccd5c1a19a682455ed4efa39dadd6"
      - name: SablierFlow_v1_1
        address: "0x555b0766f494c641bb522086da4e728ac08c1420"
  - id: 42161
    start_block: 281305357
    contracts:
      - name: SablierFlow_v1_0
        address: "0x18a12a7035aa56240bcd236bc019aa245dcc015a"
      - name: SablierFlow_v1_1
        address: "0x87cf87ec5de33deb4a88787065373563ba85ee72"
  - id: 43114
    start_block: 53922039
    contracts:
      - name: SablierFlow_v1_0
        address: "0x8c172e42c06302e3cfe555dc4d6b71a756ee186b"
      - name: SablierFlow_v1_1
        address: "0xac7cb985d4022a5ebd4a385374ac3d3b487b3c63"
  - id: 8453
    start_block: 23269999
    contracts:
      - name: SablierFlow_v1_0
        address: "0x1a9adc0e2114c8407cc31669baafeee031d15dd2"
      - name: SablierFlow_v1_1
        address: "0x6fe93c7f6cd1dc394e71591e3c42715be7180a6a"
  - id: 80094
    start_block: 780382
    contracts:
      - name: SablierFlow_v1_1
        address: "0xa031544946ed769377128fbd961c9d621c4b4179"
  - id: 81457
    start_block: 12259771
    contracts:
      - name: SablierFlow_v1_0
        address: "0xfdac2799644141856e20e021ac06f231cafc731f"
      - name: SablierFlow_v1_1
        address: "0x16b50eb5eaef0366f1a4da594e2a8c8943a297e0"
  - id: 56
    start_block: 44582847
    contracts:
      - name: SablierFlow_v1_0
        address: "0xfce01f79247cf450062545e7155d7bd568551d0e"
      - name: SablierFlow_v1_1
        address: "0x4c4610af3f3861ec99b6f6f8066c03e4c3a0e023"
  - id: 88888
    start_block: 19125673
    hypersync_config:
      url: https://chiliz.hypersync.xyz
    contracts:
      - name: SablierFlow_v1_0
        address: "0x9efc8663cab0e2d97ad17c9fbfc8392445517e94"
      - name: SablierFlow_v1_1
        address: "0x28eab88ee8a951f78e1028557d0c3fd97af61a33"
  - id: 1
    start_block: 21330577
    contracts:
      - name: SablierFlow_v1_0
        address: "0x2d9221a63e12aa796619cb381ec4a71b201281f5"
      - name: SablierFlow_v1_1
        address: "0x3df2aaede81d2f6b261f79047517713b8e844e04"
  - id: 478
    start_block: 3359543
    contracts:
      - name: SablierFlow_v1_1
        address: "0x5dd399bb320412df92df5c10484d3f8d481fe231"
  - id: 100
    start_block: 37356094
    contracts:
      - name: SablierFlow_v1_0
        address: "0x5515f774a4db42820802333ba575f68a6e85bd13"
      - name: SablierFlow_v1_1
        address: "0x34bc0c2bf1f2da51c65cd821ba4133afcacdb8f5"
  - id: 4689
    start_block: 33533023
    contracts:
      - name: SablierFlow_v1_0
        address: "0x1ddc1c21cd39c2fa16366e6036c95342a31831ba"
      - name: SablierFlow_v1_1
        address: "0xcd8871a22640c57ba36984fb57e9c794f5df7f40"
  - id: 1890
    start_block: 116397460
    contracts:
      - name: SablierFlow_v1_0
        address: "0x46fa0164c5af9382d330e5a245a2ca8a18398950"
      - name: SablierFlow_v1_1
        address: "0x89d964e0b508234bcfdc7a32ae0aa0356f422b70"
  - id: 59144
    start_block: 12929891
    contracts:
      - name: SablierFlow_v1_0
        address: "0x949bfa08f1632432a2656a9db17ca34d54da8296"
      - name: SablierFlow_v1_1
        address: "0xefc6e4c7dc5faa0cfbfebb5e04ea7cd47f64012f"
  - id: 34443
    start_block: 16616938
    hypersync_config:
      url: https://mode.hypersync.xyz
    contracts:
      - name: SablierFlow_v1_0
        address: "0x75970dde488431fc4961494569def3269f20d6b3"
      - name: SablierFlow_v1_1
        address: "0xc968e8eefe19bd6de8868df40d9740be127a172a"
  - id: 2818
    start_block: 980797
    hypersync_config:
      url: https://morph.hypersync.xyz/
    contracts:
      - name: SablierFlow_v1_0
        address: "0xfe6972d0ae797fae343e5a58d0c7d8513937f092"
      - name: SablierFlow_v1_1
        address: "0xf31c8e7d9a0bd310a9d5fb317ba67bb1f0101c6d"
  - id: 10
    start_block: 128865315
    contracts:
      - name: SablierFlow_v1_0
        address: "0x906356e4e6410ea0a97dbc5b071cf394ab0dcd69"
      - name: SablierFlow_v1_1
        address: "0xc5612fea2d370127ac67048115bd6b1df7b7f7c0"
  - id: 137
    start_block: 65079319
    contracts:
      - name: SablierFlow_v1_0
        address: "0xcf2d812d5aad4e6fec3b05850ff056b21159d496"
      - name: SablierFlow_v1_1
        address: "0x3e5c4130ea7cfbd364fa5f170289d697865ca94b"
  - id: 534352
    start_block: 11643209
    contracts:
      - name: SablierFlow_v1_0
        address: "0x66826f53bffeaab71adc7fe1a77e86f8268848d8"
      - name: SablierFlow_v1_1
        address: "0xc4f104ce12cb12484ff67cf0c4bd0561f0014ec2"
  - id: 1329
    start_block: 138911958
    contracts:
      - name: SablierFlow_v1_1
        address: "0xdef70082ebda4944a55311624900e42a720b4ec9"
  - id: 5330
    start_block: 3610744
    hypersync_config:
      url: https://extrabud.hypersync.xyz
    contracts:
      - name: SablierFlow_v1_0
        address: "0x4f5f9b3fb57bba43aaf90e3f71d8f8f384e88e20"
      - name: SablierFlow_v1_1
        address: "0x40e75bb2f2aa3507d3a332872829c71be19ef623"
  - id: 5845
    start_block: 3296266
    hypersync_config:
      url: https://tangle.hypersync.xyz
    contracts:
      - name: SablierFlow_v1_0
        address: "0xcff4a803b0bf55dd1be38fb96088478f3d2eecf2"
      - name: SablierFlow_v1_1
        address: "0xcb099efc90e88690e287259410b9ae63e1658cc6"
  - id: 19991
    start_block: 4858957
    contracts:
      - name: SablierFlow_v1_1
        address: "0xaf210dd54870745ed18f1081252aeee4119ea6ca"
  - id: 130
    start_block: 13883575
    contracts:
      - name: SablierFlow_v1_1
        address: "0x9797b40340be0bfc9ec0dbb8712627bcdd17e771"
  - id: 50
    start_block: 85226840
    contracts:
      - name: SablierFlow_v1_1
        address: "0xd6482334242862951da3e730f818c3f6e3f45a30"
  - id: 324
    start_block: 50572220
    contracts:
      - name: SablierFlow_v1_0
        address: "0x015899a075b7c181e357cd0ed000683dbb4f1fce"
      - name: SablierFlow_v1_1
        address: "0xe3747379bf7282e0ab5389a63ea053a5256042df"
  - id: 421614
    start_block: 103460016
    contracts:
      - name: SablierFlow_v1_0
        address: "0x781b3b2527f2a0a1e6b429161f2717a8a28b9f46"
      - name: SablierFlow_v1_1
        address: "0xf9cbffae10010475a2800a5efc11f4d4780ca48d"
  - id: 84532
    start_block: 18780695
    contracts:
      - name: SablierFlow_v1_0
        address: "0xd5f78708d83ac2bc8734a8cdf2d112c1bb3b62a2"
      - name: SablierFlow_v1_1
        address: "0xfb6b72a5988a7701a9090c56936269241693a9cc"
  - id: 11155111
    start_block: 7210716
    contracts:
      - name: SablierFlow_v1_0
        address: "0x5ae8c13f6ae094887322012425b34b0919097d8a"
      - name: SablierFlow_v1_1
        address: "0x93fe8f86e881a23e5a2feb4b160514fd332576a6"
  - id: 11155420
    start_block: 20763576
    contracts:
      - name: SablierFlow_v1_0
        address: "0x417db0f2bd020fc4d6bccea6b2bb6be0c541862e"
      - name: SablierFlow_v1_1
        address: "0x77873085a88189c8b82b3a01bcbc294108d02805"
  - id: 300
    start_block: 4276904
    contracts:
      - name: SablierFlow_v1_0
        address: "0x8e70296f8972ebe94d885b1caf94da4836976140"
      - name: SablierFlow_v1_1
        address: "0xf499b35e2e932a05ecd6115aa4dcceb29af55e3d"
```

</p>
</details>
